// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status info for a single bridge.
 */
export type BridgeStatusInfo = { id: bigint, name: string, connected: boolean, };
