// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Application = { id: bigint, user_id: bigint, name: string, description: string | null, token: string, default_priority: number, image: string | null, created_at: string, updated_at: string, retention_days: number | null, };
