// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight attachment info included in message responses
 */
export type AttachmentInfo = { id: bigint, name: string, type: string | null, size: bigint, url: string, };
