// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Attachment = { id: bigint, message_id: bigint, filename: string, content_type: string | null, size_bytes: bigint, storage_type: string, storage_path: string, expires_at: string | null, created_at: string, };
