// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageAction } from "./MessageAction";

/**
 * Enhanced message creation (via topic)
 */
export type CreateTopicMessage = { title: string | null, message: string, priority: number | null, tags: Array<string> | null, click_url: string | null, icon_url: string | null, actions: Array<MessageAction> | null, scheduled_for: string | null, };
