// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageResponse } from "./MessageResponse";
import type { Paging } from "./Paging";

export type PagedMessages = { messages: Array<MessageResponse>, paging: Paging, };
