// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopicPermission = { id: bigint, user_id: bigint, topic_pattern: string, can_read: boolean, can_write: boolean, };
