// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateApplication = { name: string | null, description: string | null, default_priority: number | null, retention_days: number | null, };
