// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateMqttBridge = { name: string | null, remote_url: string | null, subscribe_topics: Array<string> | null, publish_topics: Array<string> | null, username: string | null, password: string | null, qos: number | null, topic_prefix: string | null, auto_create_topics: boolean | null, enabled: boolean | null, };
