// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebhookDeliveryLog = { id: bigint, webhook_config_id: bigint, message_id: bigint | null, status_code: number | null, response_body_preview: string | null, duration_ms: bigint, attempted_at: string, success: boolean, };
